### ISSUE TITLE
Have you successfully used OP-TEE on the ultra96-v2 board?

### ISSUE THREAD

**Issue by StephQAZ** [janoslim/janoslim.github.io#1]
hello, I have an ultra96-v2 board, and I want to use op-tee in ARM secure world. I see your issue on the optee-os repo. so I have the same question that does op-tee only support ultra96-v1? If you have relevant experience, you can tell me, thank you.

**Comment by janoslim** [comment]
I just change to another board for my test. Sorry I cant help you.

**Comment by StephQAZ** [comment]
thank you for your reply.

**Comment by StephQAZ** [comment]
Hello, I have a new problem that you may encountered before.


I use the petalinux v2018.2 and&nbsp;ultra96v2_oob_2018_3.bsp, and my optee gits version is 3.12.0. When I make the zynqmp.mk(my optee-build version is v3.12.0), that's an error that happened in 'petalinux-build' command.


The log is bellow:
---------------------------------------------------------------------------------------------------------------------------------------------------------
[INFO] building project
[INFO] sourcing bitbake
INFO: bitbake petalinux-user-image
WARNING: /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx_2018.2.bb: Unable to get checksum for linux-xlnx SRC_URI entry bsp.cfg: file could not be found
Parsing recipes: 100% |###############################################################| Time: 0:01:33
Parsing of 2567 .bb files complete (0 cached, 2567 parsed). 3461 targets, 135 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
Initialising tasks: 100% |############################################################| Time: 0:00:04
Checking sstate mirror object availability: 100% |####################################| Time: 0:01:32
WARNING: The glib-2.0:do_install sig is computed to be c82b25171da8515e5800d74a70d42c93, but the sig is locked to 5a8b7eae80698703db3d567d97fae75c in SIGGEN_LOCKEDSIGS_t-aarch64
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba-r0 do_fetch: Failed to fetch URL file://bsp.cfg, attempting MIRRORS if available
ERROR: linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba-r0 do_fetch: Fetcher failure: Unable to find file file://bsp.cfg anywhere. The paths that were searched were:
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/v2018.2
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/v2018.2
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/v2018.2
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/v2018.2
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/v2018.2
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/v2018.2
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/v2018.2
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/v2018.2
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/petalinux
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/petalinux
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/petalinux
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/petalinux
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/petalinux
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/petalinux
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/petalinux
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/petalinux
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/aarch64
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/aarch64
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/ultra96-zynqmp
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/ultra96-zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/ultra96-zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/ultra96-zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/ultra96-zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/ultra96-zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/ultra96-zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/ultra96-zynqmp
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/zynqmp
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/zynqmp
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/zynqmp
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/zynqmpeg
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/zynqmpeg
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/zynqmpeg
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/zynqmpeg
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/zynqmpeg
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/zynqmpeg
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/zynqmpeg
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/zynqmpeg
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/mali400
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/mali400
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/mali400
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/mali400
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/mali400
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/mali400
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/mali400
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/mali400
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/aarch64
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/aarch64
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/aarch64
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/project-spec/meta-plnx-generated/recipes-kernel/linux/configs/
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-openamp/recipes-kernel/linux/config/
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-contrib/recipes-kernel/linux/linux-xlnx/
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba/
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx/
&nbsp; &nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/files/
&nbsp; &nbsp; /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/build/downloads
ERROR: linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba-r0 do_fetch: Fetcher failure for URL: 'file://bsp.cfg'. Unable to fetch URL from any source.
ERROR: linux-xlnx-4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/st/Desktop/optee3.12.0/ultra96-reva-2018.2/build/tmp/work/ultra96_zynqmp-xilinx-linux/linux-xlnx/4.14-xilinx-v2018.2+gitAUTOINC+ad4cd988ba-r0/temp/log.do_fetch.52964
ERROR: Task (/home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx_2018.2.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1839 tasks of which 1837 didn't need to be rerun and 1 failed.


Summary: 1 task failed:
&nbsp; /home/st/Desktop/petalinux/2018.2/components/yocto/source/aarch64/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx_2018.2.bb:do_fetch
Summary: There were 3 WARNING messages shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
ERROR: Failed to build project
zynqmp.mk:91: recipe for target 'petalinux-build' failed
make: *** [petalinux-build] Error 255

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I don't know whether you have met this error. If you can give me some advice, I would appreciate you.


Thank you.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "janoslim/janoslim.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [janoslim/janoslim.github.io] Have you successfully used OP-TEE on the ultra96-v2 board? (Issue #1)





 
I just change to another board for my test. Sorry I cant help you.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by janoslim** [comment]
Sorry, I have no idea on this issue since it has been a year do sth on ultra board. As I skim on logs it seems like some links are invalid.
